name: AmethystEvents
version: ${project.version}
main: co.uk.lostanddead.amethystevents.AmethystEvents
api-version: 1.17
authors: [ LostAndDead ]
description: Amethyst Events System
website: https://lostanddead.co.uk
permissions:
  events.reload:
    description: Allows users to reload events
    default: false

commands:
  event:
    description: Gets info on the current event
    usage: /<command>
  beginapocalypse:
    usage: /<command>
    permission: events.reload
    permission-message: ""
  sendprep:
    usage: /<command>
    permission: events.reload
    permission-message: ""
  summonboss:
    usage: /<command>
    permission: events.reload
    permission-message: ""