name: AmethystEvents
version: 1.0-SNAPSHOT
main: co.uk.lostanddead.amethystevents.AmethystEvents
api-version: 1.16
authors: [ LostAndDead ]
description: Amethyst Events System
website: https://lostanddead.co.uk

commands:
  event:
    description: Gets info on the current event
    usage: /<command>

permissions:
  event.reload:
    description: Allows users to reload events
    default: false