name: AmethystEvents
version: 1.0-SNAPSHOT
main: co.uk.lostanddead.amethystevents.AmethystEvents
api-version: 1.17
authors: [ LostAndDead ]
description: Amethyst Events System
website: https://lostanddead.co.uk
load: POSTWORLD

commands:
  event:
    description: Gets info on the current event
    usage: /<command>
  beginapocalypse:
    usage: /<command>
  sendprep:
    usage: /<command>
  summonboss:
    usage: /<command>
